name: user_auth
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  firebase_app_check: ^0.2.2+4
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  logger: ^2.2.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  sign_button: ^2.0.6
  twitter_login: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  # flutter_lints: ^3.0.0
  # flutter_launcher_icons: "^0.13.1"

  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/splash/user_auth_splash_light.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/user-auth/
    - assets/icons/splash/
    - assets/fonts/
